name: Build-Backend

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./hotchpotch-backend

jobs:
  build-without-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle (without testing)
        run: ./gradlew build -x test
